sonar.projectKey=Subiahn
sonar.organization=subiahn

# 프로젝트 정보
sonar.projectName=zero-trust-container-security
sonar.projectVersion=1.0

# 분석할 소스 경로
sonar.sources=app
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**

# Python 설정
sonar.python.version=3.11

# 인코딩
sonar.sourceEncoding=UTF-8